apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app: foo-echo
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: http-echo
    patch: |-
      - op: replace
        path: /metadata/name
        value: foo-echo
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "-text=foo"
          - "-listen=:8080"
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/labelSelector/matchExpressions/0/values
        value:
          - foo-echo
  - target:
      kind: Service
      name: http-echo-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: foo-echo-service
