apiVersion: v1
kind: Service
metadata:
  name: http-echo-service
  labels:
    app: http-echo
    component: http-echo
spec:
  type: ClusterIP
  selector:
    app: http-echo
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
