apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

labels:
  - pairs:
      app: bar-echo
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: http-echo
    patch: |-
      - op: replace
        path: /metadata/name
        value: bar-echo
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - "-text=bar"
          - "-listen=:8080"
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/labelSelector/matchExpressions/0/values
        value:
          - bar-echo
  - target:
      kind: Service
      name: http-echo-service
    patch: |-
      - op: replace
        path: /metadata/name
        value: bar-echo-service
