apiVersion: v1
kind: Service
metadata:
  name: foo-echo-service
  namespace: default
  labels:
    app: foo-echo
    component: http-echo
spec:
  type: ClusterIP
  selector:
    app: foo-echo
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: None
